title: Welcome !
author: Kaede Rukawa
email: antsoitokiana@outlook.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
 This is my blog. Hope y'all will like like it.
 I will still post after a few but for now I do not have any inspiration.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Kaede-Rukawa11

show_excerpts: true # set to false to remove excerpts on the homepage
